cart/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
app_name='cart'

urlpatterns = [
    path('add-to-cart/<slug>',add_to_cart,name='add-to-cart'),
    path('my_cart',CartView.as_view(),name='my_cart'),
    path('delete_cart/<slug>',delete_cart,name='delete_cart'),
    path('add/<slug>',add,name='add'),
    path('subtract/<slug>',subtract,name='subtract'),
    path('my_wishlist/',WishlistView.as_view(),name='my_wishlist'),
    path('add-wish-list/<slug>',add_wish_list,name='add-wish-list'),
    path('delete_wishlist/<slug>',delete_wishlist,name='delete_wishlist'),
    path('add_wish/<slug>',add_wish,name='add_wish'),
    path('subtract_wish/<slug>',subtract_wish,name='subtract_wish'),

]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace= 'home')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('cart/',include('cart.urls',namespace= 'cart')),
    path('api/',include('home.api_urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
app_name='home'

urlpatterns = [
    path('',HomeView.as_view(),name='home'),
    path('category/<slug>',CategoryItemView.as_view(),name='category'),
    path('item_detail/<slug>',ItemDetailView.as_view(),name='item_detail'),
    path('brand_items/<slug>',BrandItemView.as_view(),name='brand_items'),
    path('search',ItemSearchView.as_view(),name='search'),
    path('signup',signup,name='signup'),
    path('api_data',api_data,name='api_data'),

]

cart/models.py
from django.db import models
from home.models import *

# Create your models here.
class Cart(models.Model):
    username=models.CharField(max_length=500)
    items=models.ForeignKey(Item,on_delete=models.CASCADE)
    slug=models.CharField(max_length=300)
    quantity=models.IntegerField(default=1)
    total=models.IntegerField()
    checkout=models.BooleanField(default=False)

    def __str__(self):
        return self.username


class WishList(models.Model):
    username = models.CharField(max_length=500)
    items = models.ForeignKey(Item, on_delete=models.CASCADE)
    slug = models.CharField(max_length=300)
    quantity = models.IntegerField(default=1)
    add_to_cart = models.BooleanField(default=False)

    def __str__(self):
        return self.username

home/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
STATUS=(('active','Active'),('inactive','Inactive'))
LABEl=(('new','New'),('old','Old'),('hot','Hot'),('','default'))
class Category(models.Model):
    name=models.CharField(max_length=200)
    logo=models.CharField(max_length=200,blank=True)
    slug=models.CharField(max_length=300)
    status=models.CharField(choices=STATUS,max_length=200)
    def __str__(self):
        return self.name

class Slider(models.Model):
    name = models.CharField(max_length=200)
    image=models.ImageField(upload_to='media')
    description=models.TextField()
    status = models.CharField(choices=STATUS, max_length=200)

    def __str__(self):
        return self.name

class Ad(models.Model):
    name = models.CharField(max_length=300)
    image = models.ImageField(upload_to='media')
    description = models.TextField(blank=True)
    rank=models.IntegerField()
    status = models.CharField(choices=STATUS, max_length=200)
    def __str__(self):
        return self.name
class Brand(models.Model):
    name = models.CharField(max_length=300)
    image = models.ImageField(upload_to='media',blank=True,null=True)
    status = models.CharField(choices=STATUS, max_length=200)

    def __str__(self):
        return self.name
class Item(models.Model):
    name = models.CharField(max_length=300)
    price=models.IntegerField()
    discounted_price=models.IntegerField(default=0)
    image = models.ImageField(upload_to='media')
    category =models.ForeignKey(Category,on_delete=models.CASCADE)
    brand= models.ForeignKey(Brand,on_delete=models.CASCADE,blank=True,null=True)
    label=models.CharField(choices=LABEl,max_length=200,blank=True)
    status = models.CharField(choices=STATUS, max_length=200)
    description = models.TextField(blank=True)
    specification=models.TextField(blank=True)
    slug = models.CharField(max_length=300)

    def __str__(self):
        return self.name

    def add_to_cart(self):
       return reverse('cart:add-to-cart',kwargs= {'slug':self.slug })

cart/views.py
from django.shortcuts import render,redirect
from .models import *
from home.views import *
from django.core.mail import EmailMessage
def add_to_cart(request,slug):
    username = request.user.username
    price = Item.objects.get(slug=slug).price
    discounted_price=Item.objects.get(slug=slug).price
    if discounted_price > 0:
        original_price=discounted_price
    else:
        original_price=price
    if Cart.objects.filter(username=username,slug=slug,checkout=False).exists():
        quantity=Cart.objects.get(username=username,slug=slug,checkout=False).quantity
        quantity=quantity+1
        total=original_price*quantity
        Cart.objects.filter(username=username, slug=slug, checkout=False).update(quantity=quantity,total=total)
        return redirect('cart:my_cart')

    else:
        quantity=1
    total=original_price*quantity
    data=Cart.objects.create(
        username=username,
        items=Item.objects.filter(slug=slug)[0],
        slug=slug,
        quantity=quantity,
        total=total
    )
    data.save()
    return redirect('cart:my_cart')

class CartView(BaseView):
    def get(self,request):
        username=request.user.username
        self.views['my_cart']=Cart.objects.filter(username=username,checkout=False)
        return render(request,'cart.html',self.views)
class WishlistView(BaseView):
    def get(self,request):
        username=request.user.username
        self.views['my_wishlist']=WishList.objects.filter(username=username,add_to_cart=False)
        return render(request,'wishlist.html',self.views)
def add_wish_list(request,slug):
    username = request.user.username
    price = Item.objects.get(slug=slug).price
    discounted_price = Item.objects.get(slug=slug).discounted_price
    if WishList.objects.filter(username=username, slug=slug, add_to_cart=False).exists():
        quantity = WishList.objects.get(username=username, slug=slug, add_to_cart=False).quantity
        quantity = quantity + 1
        WishList.objects.filter(username=username, slug=slug, add_to_cart=False).update(quantity=quantity)
        return redirect('cart:my_cart')

    else:
        quantity = 1
    data = WishList.objects.create(
        username=username,
        items=Item.objects.filter(slug=slug)[0],
        slug=slug,
        quantity=quantity,
    )
    data.save()
    return redirect('cart:my_wishlist')
def add_wish(request,slug):
    username = request.user.username
    price = Item.objects.get(slug=slug).price
    discounted_price = Item.objects.get(slug=slug).price
    if WishList.objects.filter(username=username, slug=slug, add_to_cart=False).exists():
        quantity = WishList.objects.get(username=username, slug=slug,add_to_cart=False).quantity
        quantity = quantity + 1
        WishList.objects.filter(username=username, slug=slug, add_to_cart=False).update(quantity=quantity)
        return redirect('cart:my_wishlist')
def subtract_wish(request,slug):
    username = request.user.username
    price = Item.objects.get(slug=slug).price
    discounted_price = Item.objects.get(slug=slug).price
    if WishList.objects.filter(username=username, slug=slug, add_to_cart=False).exists():
        quantity = WishList.objects.get(username=username, slug=slug, add_to_cart=False).quantity
        if quantity >0 :
         quantity = quantity - 1
         WishList.objects.filter(username=username, slug=slug, add_to_cart=False).update(quantity=quantity)
         return redirect('cart:my_wishlist')
        else:
         return redirect('cart:my_wishlist')



def delete_wishlist(request,slug):
    username=request.user.username
    WishList.objects.filter(username=username,add_to_cart=False,slug=slug).delete()
    return redirect('cart:my_wishlist')

def delete_cart(request,slug):
    username=request.user.username
    Cart.objects.filter(username=username,checkout=False,slug=slug).delete()
    return redirect('cart:my_cart')
def add(request,slug):
    username = request.user.username
    price = Item.objects.get(slug=slug).price
    discounted_price = Item.objects.get(slug=slug).price
    if discounted_price > 0:
        original_price = discounted_price
    else:
        original_price = price
    if Cart.objects.filter(username=username, slug=slug, checkout=False).exists():
        quantity = Cart.objects.get(username=username, slug=slug, checkout=False).quantity
        quantity = quantity + 1
        total = original_price * quantity
        Cart.objects.filter(username=username, slug=slug, checkout=False).update(quantity=quantity, total=total)
        return redirect('cart:my_cart')


def subtract(request,slug):
    username = request.user.username
    price = Item.objects.get(slug=slug).price
    discounted_price = Item.objects.get(slug=slug).price
    if discounted_price > 0:
        original_price = discounted_price
    else:
        original_price = price
    if Cart.objects.filter(username=username, slug=slug, checkout=False).exists():
        quantity = Cart.objects.get(username=username, slug=slug, checkout=False).quantity
        if quantity >0 :
         quantity = quantity - 1
         total = original_price * quantity
         Cart.objects.filter(username=username, slug=slug, checkout=False).update(quantity=quantity, total=total)
         return redirect('cart:my_cart')
        else:
         return redirect('cart:my_cart')

home/views.py
from django.shortcuts import render,redirect
from django.views.generic import View
from .models import *
from django.contrib import messages
from django.contrib.auth.models import User
from rest_framework import status
import json
import requests
class BaseView(View):
    views = {}
    views['category'] = Category.objects.filter(status='active')
class HomeView(BaseView):
    def get(self,request):

        self.views['sliders']=Slider.objects.filter(status='active')
        self.views['ads']=Ad.objects.all()
        self.views['brands'] =Brand.objects.filter(status='active')
        self.views['hots']=Item.objects.filter(status='active',label='hot')
        self.views['olds']=Item.objects.filter(status='active',label='old')
        return render(request,'index.html',self.views)
class CategoryItemView(BaseView):
    def get(self,request,slug):
        category_id=Category.objects.get(slug=slug).id
        self.views['cat_items']=Item.objects.filter(category=category_id)
        return render(request,'category.html',self.views)
class BrandItemView(BaseView):
    def get(self,request,slug):
        brand_id=Brand.objects.get(slug=slug).id
        self.views['brand_items']=Item.objects.filter(brand=brand_id)
        return render(request,'category.html',self.views)
class ItemSearchView(BaseView):
    def get(self,request):
        search=request.GET.get('search',None)
        if search is None:
            return redirect('/')
        else:
            self.views['search_item']=Item.objects.filter(name__icontains=search)
            return render(request, 'search.html', self.views)

        return render(request, 'search.html', self.views)

class ItemDetailView(BaseView):
    def get(self, request, slug):
        self.views['item_detail'] = Item.objects.filter(slug=slug)
        return render(request, 'product-detail.html', self.views)

def signup(request):
    if request.method == "POST":
        f_name = request.POST['first_name']
        l_name = request.POST['last_name']
        email = request.POST['email']
        username = request.POST['username']
        password = request.POST['password']
        cpassword = request.POST['cpassword']
        if password == cpassword:
            if User.objects.filter(username = username).exists():
                messages.error(request,'This username is already taken')
                return redirect('home:signup')
            elif User.objects.filter(email = email).exists():
                messages.error(request,'This email is already taken')
                return redirect('home:signup')
            else:
                user=User.objects.create_user(
                    username=username,
                    email=email,
                    password=password,
                    first_name=f_name,
                    last_name=l_name,

                )
                user.save()
                messages.success(request,'You have successfully signed up')
                return redirect('home:signup')
        else:
            messages.error(request, 'password do not matches')
            return redirect('home:signup')

    return render(request,'signup.html')

# -----------------------------------------api-------------------------------------------------------------

from rest_framework import routers, serializers, viewsets
# from django.contrib.auth.models import User
from rest_framework import generics
from .serializers import *
from .models import *
from rest_framework.filters import OrderingFilter,SearchFilter
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.views import APIView
from rest_framework.response import Response
from django.http import Http404



# ViewSets define the view behavior.
class ItemViewSet(viewsets.ModelViewSet):
    queryset = Item.objects.all()
    serializer_class = ItemSerializer

class FilterItemViewSet(generics.ListAPIView):
    queryset = Item.objects.all()
    serializer_class = ItemSerializer
    filter_backends = [DjangoFilterBackend,OrderingFilter,SearchFilter]
    filter_field=['id','category','label']
    ordering_field=['id','price','title']
    search_field=['title','description']

class ItemDetail(APIView):
    def get_object(selfself,pk):
        try:
            return Item.objects.get(id = pk)
        except:
            raise Http404
    def get(self,request, pk):
        object=self.get_object(pk)
        serializers=ItemSerializer(object,data=request.data)
        if serializers.is_valid():
            serializers.save()
            return Response(serializers.data)
        else:
            pass
        return Response(serializers.errors,status=status.HTTP_400_BAD_REQUEST)
    def delete(self,request,pk):
        object=self.get(pk)
        object.delete()
        return Response("The row is deleted.",status=status.HTTP_202_OK)
api_url='http://127.0.0.1:8000/api/item/'
def api_data(request):
    response=requests.get(api_url)
    records=response.text
    records=json.loads(records)
    return render(request,'api.html',{'items':records})

home/templates/api.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for i in items %}
{{i.name}}

{% endfor %}
</body>
</html>

home/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>E Store - eCommerce HTML Template</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="eCommerce HTML Template Free Download" name="keywords">
        <meta content="eCommerce HTML Template Free Download" name="description">

        <!-- Favicon -->
        <link href="{% static 'img/favicon.ico' %}" rel="icon">

        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400|Source+Code+Pro:700,900&display=swap" rel="stylesheet">

        <!-- CSS Libraries -->
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        <link href="{% static 'lib/slick/slick.css' %}" rel="stylesheet">
        <link href="{% static 'lib/slick/slick-theme.css' %}" rel="stylesheet">

        <!-- Template Stylesheet -->
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
    </head>

    <body>
        <!-- Top bar Start -->
        <div class="top-bar">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-6">
                        <i class="fa fa-envelope"></i>
                        support@email.com
                    </div>
                    <div class="col-sm-6">
                        <i class="fa fa-phone-alt"></i>
                        +012-345-6789
                    </div>
                </div>
            </div>
        </div>
        <!-- Top bar End -->

        <!-- Nav Bar Start -->
        <div class="nav">
            <div class="container-fluid">
                <nav class="navbar navbar-expand-md bg-dark navbar-dark">
                    <a href="#" class="navbar-brand">MENU</a>
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                        <div class="navbar-nav mr-auto">
                            <a href="/" class="nav-item nav-link">Home</a>
                        </div>
                        {% if user.is_authenticated %}
                        <div class="navbar-nav ml-auto">
                            <div class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">{{user.username}}</a>
                                <div class="dropdown-menu">
                                    <a href="/accounts/logout" class="dropdown-item">Logout</a>
                                </div>
                            </div>
                        </div>
                        {% else %}
                        <div class="navbar-nav ml-auto">
                            <div class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">User Account</a>
                                <div class="dropdown-menu">
                                    <a href="/accounts/login" class="dropdown-item">Login</a>
                                    <a href="/signup" class="dropdown-item">Register</a>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                </nav>
            </div>
        </div>
        <!-- Nav Bar End -->

        <!-- Bottom Bar Start -->
        <div class="bottom-bar">
            <div class="container-fluid">
                <div class="row align-items-center">
                    <div class="col-md-3">
                        <div class="logo">
                            <a href="index.html">
                                <img src="static 'img/logo.png'" alt="Logo">
                            </a>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <form method="GET" action="{% url 'home:search'%}">
                        <div class="search">
                            <input name="search" type="text" placeholder="Search">
                            <button type="submit"><i class="fa fa-search"></i></button>
                        </div>
                        </form>>
                    </div>
                    <div class="col-md-3">
                        <div class="user">
                            <a href="wishlist.html" class="btn wishlist">
                                <i class="fa fa-heart"></i>
                                <span>(0)</span>
                            </a>
                            <a href="cart.html" class="btn cart">
                                <i class="fa fa-shopping-cart"></i>
                                <span>(0)</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Bottom Bar End -->

{% block content %}
{% endblock %}

        <!-- Footer Start -->
        <div class="footer">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Get in Touch</h2>
                            <div class="contact-info">
                                <p><i class="fa fa-map-marker"></i>Badhare,Jamune, Tanahun</p>
                                <p><i class="fa fa-envelope"></i>business@example.com</p>
                                <p><i class="fa fa-phone"></i>9815011205</p>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Follow Us</h2>
                            <div class="contact-info">
                                <div class="social">
                                    <a href=""><i class="fab fa-twitter"></i></a>
                                    <a href=""><i class="fab fa-facebook-f"></i></a>
                                    <a href=""><i class="fab fa-linkedin-in"></i></a>
                                    <a href=""><i class="fab fa-instagram"></i></a>
                                    <a href=""><i class="fab fa-youtube"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Company Info</h2>
                            <ul>
                                <li><a href="#">About Us</a></li>
                                <li><a href="#">Privacy Policy</a></li>
                                <li><a href="#">Terms & Condition</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Purchase Info</h2>
                            <ul>
                                <li><a href="#">Pyament Policy</a></li>
                                <li><a href="#">Shipping Policy</a></li>
                                <li><a href="#">Return Policy</a></li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="row payment align-items-center">
                    <div class="col-md-6">
                        <div class="payment-method">
                            <h2>We Accept:</h2>
                            <img src="img/payment-method.png" alt="Payment Method" />
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="payment-security">
                            <h2>Secured By:</h2>
                            <img src="img/godaddy.svg" alt="Payment Security" />
                            <img src="img/norton.svg" alt="Payment Security" />
                            <img src="img/ssl.svg" alt="Payment Security" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->

        <!-- Footer Bottom Start -->
        <div class="footer-bottom">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 copyright">
                        <p>Copyright &copy; <a href="https://htmlcodex.com">HTML Codex</a>. All Rights Reserved</p>
                    </div>

                    <div class="col-md-6 template-by">
                        <p>Template By <a href="https://htmlcodex.com">HTML Codex</a></p>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer Bottom End -->

        <!-- Back to Top -->
        <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

        <!-- JavaScript Libraries -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <script src="{% static 'lib/easing/easing.min.js' %}"></script>
        <script src="{% static 'lib/slick/slick.min.js' %}"></script>

        <!-- Template Javascript -->
        <script src="{% static 'js/main.js' %}"></script>
    </body>
</html>

home/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content%}
        
        <!-- Breadcrumb Start -->
        <div class="breadcrumb-wrap">
            <div class="container-fluid">
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item"><a href="#">Products</a></li>
                    <li class="breadcrumb-item active">Cart</li>
                </ul>
            </div>
        </div>
        <!-- Breadcrumb End -->
        
        <!-- Cart Start -->
        <div class="cart-page">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-8">
                        <div class="cart-page-inner">
                            <div class="table-responsive">
                                <table class="table table-bordered">
                                    <thead class="thead-dark">
                                        <tr>
                                            <th>Product</th>
                                            <th>Price</th>
                                            <th>Quantity</th>
                                            <th>Total</th>
                                            <th>Remove</th>
                                        </tr>
                                    </thead>
                                    <tbody class="align-middle">
                                    {% for cart in my_cart %}
                                        <tr>
                                            <td>
                                                <div class="img">
                                                    <a href="#"><img src="{{cart.items.image.url}}" alt="Image"></a>
                                                    <p>"{{cart.items.name.url}}</p>
                                                </div>
                                            </td>
                                            {% if cart.items.discounted_price > 0 %}
                                            <td>Rs{{cart.items.discounted_price}}</td>
                                            {% else %}
                                            <td>Rs{{cart.items.price}}</td>
                                            {% endif %}
                                            <td>
                                                <div class="qty">

                                                    <a href="/cart/subtract/{{cart.items.slug}}"> <button class="btn-minus"><i class="fa fa-minus"></i></button></a>
                                                    <input type="text" value="{{cart.quantity}}">
                                                    <a href="/cart/add/{{cart.items.slug}}"> <button class="btn-plus"><i class="fa fa-plus"></i></button></a>
                                                </div>
                                            </td>
                                            <td>Rs{{cart.total}}</td>
                                            <td><a href="/cart/delete_cart/{{cart.items.slug}}"><button><i class="fa fa-trash"></i></button></a></td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="cart-page-inner">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="coupon">
                                        <input type="text" placeholder="Coupon Code">
                                        <button>Apply Code</button>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="cart-summary">
                                        <div class="cart-content">
                                            <h1>Cart Summary</h1>
                                            <p>Sub Total<span>$99</span></p>
                                            <p>Shipping Cost<span>$1</span></p>
                                            <h2>Grand Total<span>$100</span></h2>
                                        </div>
                                        <div class="cart-btn">
                                            <button><a href="#">Update</a></button>
                                            <button><a href="#">Checkout</a></button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Cart End -->
        {% endblock %}